config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "categories#index"
  resources :categories
  resources :projects do
    resources :comments, only: :create
    post :like, on: :member
    get :favorite, on: :collection
    get :search, on: :collection
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true
  has_many :projects, dependent: :destroy
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :title, presence: true
  validates :cover, presence: true
  validates :description, presence: true
  validates :category_id, presence: true
  validates :url, presence: true

  belongs_to :category, counter_cache: true
  has_many :comments, dependent: :destroy
  has_many :user_project_relationships
  has_many :users, through: :user_project_relationships
  
  def self.search(input)
    where( "title LIKE ? or description LIKE ?", "%#{input}%", "%#{input}%")
  end  
  
  def add_project_information
    
    begin
      object = LinkThumbnailer.generate(url)
    rescue
      return false
    end
    
    if !object.nil?
      self.title = object.title
      self.description = object.description
      self.cover = object.images.first.src.to_s if object.images.length != 0 
      return true
    end
    
  end  
  
  def like_by_user?(user)
    user.projects.include?(self)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :comments
  has_many :user_project_relationships
  has_many :projects, through: :user_project_relationships
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_project_relationship.rb
class UserProjectRelationship < ActiveRecord::Base
  belongs_to :user, touch: true
  belongs_to :project, touch: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :name
      devise_parameter_sanitizer.for(:account_update) << :name
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end
  
  def show
    @category = Category.includes(:projects).find_by(id: params[:id])
    @projects = @category.projects.order("created_at DESC")
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  
  def create
    project = Project.find_by(id: params[:project_id])
    @comment = Comment.new(comment_params)
    @comment.project = project
    @comment.save
    @new_counts = project.comments.count
    
    respond_to do |format|
      format.js
    end
  end
  
  private
    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, only: [:show, :edit, :update, :destroy, :like]
  before_action :authenticate_user!, except: [:show, :search]
  before_action :admin_user?, except: [:show, :favorite, :like, :search]
  
  def new
    @project = Project.new
    @categories = Category.all
  end
  
  def favorite 
    @projects = current_user.projects
  end
  
  def search
    if params[:search_content].blank?
      @projects = [] and return
    end
    
    @search_content = params[:search_content]
    @projects = Project.search(params[:search_content]).order('updated_at DESC')  
    
  end

  def create
    
    if Project.exists?(url: params[:project][:url])
      @message = "Already existed" 
      return
    end
    
    @project = Project.new(project_params)
    if @project.add_project_information
      if @project.save
        @message = "Successfully added"
      else
        @message = "Wrong data"  
      end
    else
      @message = "Invalid URL" 
    end

    respond_to do |format|
      format.js
    end
    
  end
  
  def like
    if @project.like_by_user? current_user
      current_user.projects.delete(@project)
      @like = false
    else
      current_user.projects << @project 
      @like = true
    end
    
    
    respond_to do |format|
      format.js
    end
    
  end
  
  def show
    if user_signed_in?
      @like = @project.like_by_user? current_user
    end
    @comments = @project.comments.order("created_at DESC")
    @comment = @project.comments.new
  end
  
  def edit
    @categories = Category.all
  end
  
  def update
    if @project.update(project_params)
      redirect_to project_path(@project) 
    else
      render 'edit'
    end
  end
  
  def destroy
    @project.destroy
    redirect_to root_path
  end
  
  
  private
    def project_params
      params.require(:project).permit(:url, :category_id, :description, :title, :cover)
    end  
  
    def find_project
      @project = Project.find_by(id: params[:id])
    end
    
    def admin_user?
      if !current_user.admin
        redirect_to root_path
      end
    end    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/categories/index.html.erb
<div class="jumbotron text-center">
  <h1>Welcome to BackStarter</h1> 
  <p>We pick the hotest projects for you! Enjoy it!</p> 
  <%= link_to "View Projects", "#categories", class: "btn btn-lg btn-default", id: "btn-view-project" %>
</div>


<div class="container" id="categories">
  <h2 class="text-center">CATEGORIES</h2>
  <div class="spacer"></div>
  <br>
  <% @categories.each do |category|%>
  <div class="col-md-3 col-sm-6">
    <div class="panel panel-default">
      <%= link_to category, class: "categories-link" do %>
      <div class="panel-heading text-center"><%= category.name %></div>
      <div class="panel-body">
        <%= image_tag "categories/#{category.name}.jpg", class: "categories_image" %>
        <div class="projects_count text-center">
          <span class="glyphicon glyphicon-stats"></span> &nbsp;<%= pluralize(category.projects_count,'project') %>
        </div>
      </div> 
      <% end %>
    </div>    
  </div>
  <% end %>
</div>
<footer class="container-fluid text-center">
  <p>&copy; 2016 Ryan Yang. All rights reserved.</p> 
  <br>
  <br>
</footer>

app/views/categories/show.html.erb
<div class="container">
  <h1 class="text-center"><%= @category.name %></h1>
  <div class="spacer"></div>
  <br>
  <% if @category.projects_count == 0 %>
    <h4 class="text-center">Sorry! Please take a look at other category!</h4>
  <% else %>
    <div id="projects" class="transitions-enabled">
      <% @projects.each do |project| %>
      <div class="box panel panel-default">
        <%= link_to project, class: "project-link" do %> 
        <div class="panel-heading project_image darken">
            <%= image_tag project.cover, alt: project.description %>
          <div class="user_count_show">
            <span class="glyphicon glyphicon-heart"></span> &nbsp;<%= project.users.count %>
          </div>          
        </div>
        
        <div class="panel-body">
            <h3 class="project-title"><%= project.title %></h3>
            <p><%= truncate(project.description, length: 100) %></p>
        </div>
        <% end %>
        <div class="panel-footer">
          <div class="row">
            <div class="col-md-8 col-sm-8">
              <h5>Added <%= time_ago_in_words(project.created_at) %> ago</h5>
            </div>
            <div class="col-md-4 col-sm-4">
              <div class="btn-group pull-right">
                <% if user_signed_in? %>
                  <% if current_user.admin %>
                    <%= link_to edit_project_path(project), class: "btn btn-default" do %>
                      <span class="glyphicon glyphicon-pencil"></span>
                    <% end %>         
                  <% end %>  
                <% end %>
                <%= link_to project.url, target: "_blank", class: "btn btn-default" do %>
                  <span class="glyphicon glyphicon-link"></span>
                <% end %>                
              </div> 
            </div>
          </div>
        </div>
      </div>
      <% end %> 
    </div>
  <% end %>
</div>

app/views/comments/create.js.erb
content_to_show = '<li class="list-group-item"><p><strong><%= @comment.content %></strong><br><br>'
                + '(<%= time_ago_in_words(@comment.created_at) %>)</p></li>'
$('.list-group').prepend(content_to_show).hide().fadeIn(2000);
$('#comment-count').text('(<%= @new_counts %>)')

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BackStarter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'shared/header' %>
<div class="container-body">
  <%= yield %>
</div>
</body>
</html>

app/views/projects/create.js.erb
$("#project_url").val('');
$("#add-result").text('<%= @message %>');

<% if @message == "Successfully added" %>
    content_to_show = '<div class="col-md-6">' + '<%= image_tag "#{@project.cover}", class: "img-circle", width: "100%" %>' + '</div>'
                    + '<div class="col-md-6">' + '<h3 class="text-center"><strong><%= @project.title %></strong></h3><p><%= @project.description %></p>' + '</div>'
    $("#project-aftersave").append(content_to_show).hide().fadeIn(2000);
<% end %>

app/views/projects/edit.html.erb
<h1 class="text-center">Edit Project</h1>
<br>
<div>
<%= form_for @project, remote: true do |f| %>
  <div class="col-md-6 col-md-offset-3">
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control", :placeholder => "Enter the url" %>
    </div>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control", :placeholder => "Enter the url", rows: "10" %>
    </div>
    <div class="form-group">
      <%= select_tag "project[category_id]", options_for_select(@categories.map {|category| [category.name, category.id]}, @project.category.id), { class: "form-control" } %>
    </div>
    <div class="col-md-4">
      <div class="form-actions">
        <%= f.submit "Update", class: "btn btn-primary col-md-12", id: "btn-update-submit" %>
      </div>
    </div> 
    <div class="col-md-3 col-md-offset-5">
      <div class="form-actions">
        <%= link_to "Delete", @project, class: "btn btn-danger col-md-12", method: :delete, data: { confirm: "Are you sure?"} %>
      </div>
    </div>
  </div>   
<% end %>
</div>

app/views/projects/favorite.html.erb
<div class="container">
  <h1 class="text-center"><%= current_user.email %></h1>
  <div class="spacer"></div>
  <br>
  <% if @projects.size == 0 %>
    <h4 class="text-center">Sorry! You don't have any favorites!</h4>
  <% else %>
    <div id="projects" class="transitions-enabled">
      <% @projects.each do |project| %>
      <div class="box panel panel-default">
        <%= link_to project, class: "project-link" do %> 
        <div class="panel-heading project_image darken">
            <%= image_tag project.cover, alt: project.description %>
          <div class="user_count_show">
            <span class="glyphicon glyphicon-heart"></span> &nbsp;<%= project.users.count %>
          </div>          
        </div>
        
        <div class="panel-body">
            <h3 class="project-title"><%= project.title %></h3>
            <p><%= truncate(project.description, length: 100) %></p>
        </div>
        <% end %>
        <div class="panel-footer">
          <div class="row">
            <div class="col-md-4 col-md-offset-8 col-sm-4 col-sm-offset-4">
              <div class="btn-group pull-right">
                <%= link_to project.url, target: "_blank", class: "btn btn-default" do %>
                  <span class="glyphicon glyphicon-link"></span>
                <% end %>                
              </div> 
            </div>
          </div>
        </div>
      </div>
      <% end %> 
    </div>
  <% end %>
</div>

app/views/projects/like.js.erb
<% if @like %>
  content_to_show = '<span class="glyphicon glyphicon-heart"></span> Already liked</h4>'
<% else %>
  content_to_show = '<span class="glyphicon glyphicon-heart-empty"></span> Add to My Favorite</h4>'
<% end %>

$("#like-content").html(content_to_show).hide().fadeIn(1000);

app/views/projects/new.html.erb
<h1 class="text-center">Add A New Project</h1>
<br>
<div>
<%= form_for @project, remote: true do |f| %>
  <div class="col-md-6 col-md-offset-1">
    <div class="form-group">
      <%= f.text_field :url, class: "form-control", :placeholder => "Enter the url" %>
    </div>
  </div>
  <div class="col-md-2">
    <div class="form-group">
      <%= select_tag "project[category_id]", options_for_select(@categories.map {|category| [category.name, category.id]}), { class: "form-control" } %>
    </div>
  </div>
  <div class="col-md-3">
    <div class="form-actions">
      <%= f.submit "Add", class: "btn btn-danger col-md-6", id: "btn-add-submit" %>
    </div>
  </div>     
<% end %>
</div>
<div class="text-center" id="add-result">
</div>
<br>
<br>
<div class="container" id="project-aftersave">
</div>

app/views/projects/search.html.erb
<div class="container">
  <h1 class="text-center">The result of "<%= @search_content %>"</h1>
  <div class="spacer"></div>
  <br>
  <% if @projects.size == 0 %>
    <h4 class="text-center">Sorry! We cannot find any projects!</h4>
  <% else %>
    <div id="projects" class="transitions-enabled">
      <% @projects.each do |project| %>
      <div class="box panel panel-default">
        <%= link_to project, class: "project-link" do %> 
        <div class="panel-heading project_image darken">
            <%= image_tag project.cover, alt: project.description %>
          <div class="user_count_show">
            <span class="glyphicon glyphicon-heart"></span> &nbsp;<%= project.users.count %>
          </div>          
        </div>
        
        <div class="panel-body">
            <h3 class="project-title"><%= project.title %></h3>
            <p><%= truncate(project.description, length: 100) %></p>
        </div>
        <% end %>
        <div class="panel-footer">
          <div class="row">
            <div class="col-md-4 col-md-offset-8 col-sm-4 col-sm-offset-4">
              <div class="btn-group pull-right">
                <%= link_to project.url, target: "_blank", class: "btn btn-default" do %>
                  <span class="glyphicon glyphicon-link"></span>
                <% end %>                
              </div> 
            </div>
          </div>
        </div>
      </div>
      <% end %> 
    </div>
  <% end %>
</div>

app/views/projects/show.html.erb
<br>
<br>
<div class="container-fluid project-show">
  <div class="row">
    <div class="col-sm-6">
      <%= link_to @project.url, target: "_blank" do %>
        <%= image_tag @project.cover, alt: @project.description, class: "project-image" %>
      <% end %>
    </div>
    <div class="col-sm-6">
      <h2><strong><%= @project.title %></strong></h2>      
      <p><%= @project.description %></p>
    </div>
  </div>
  <% if user_signed_in? %>
    <div class="add-to-favorite">
      <% if @like %>
        <%= link_to like_project_path(@project), method: :post, class: "like-link btn btn-default btn-like", remote: true do %>
          <h4 class="text-center" id="like-content"><span class="glyphicon glyphicon-heart"></span> Already added</h4>
        <% end %>      
      <% else %>
        <%= link_to like_project_path(@project), method: :post, class: "like-link btn btn-default btn-like", remote: true do %>
          <h4 class="text-center" id="like-content"><span class="glyphicon glyphicon-heart-empty"></span> Add to My Favorite</h4>
        <% end %>
      <% end %>
    </div>  
  <% end %>
  <br>
  <div>
    <%= link_to "#commentModal", class: "btn btn-default", :"data-toggle" => "modal" do %>
      <h4 class="text-center">Comments <span id="comment-count">(<%= @comments.size %>)</span></h4>
    <% end %>     
  </div>
</div>


  <!-- Modal -->
  <div class="modal fade" id="commentModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title text-center">Comments</h4>
        </div>
        <div class="modal-body">
        <ul class="list-group">
          <% if @comments.size > 0 %>
            <% @comments.each do |comment| %>
              <li class="list-group-item">
                <p><strong><%= simple_format(comment.content) %></strong><br><br>
                (<%= time_ago_in_words(comment.created_at) %>)</p>
              </li>          
            <% end %>
          <% end %>  
        </ul>    
        </div>
        <div class="modal-footer">
          <% if user_signed_in? %>
            <%= form_for [@project, @comment], remote: true do |f| %>
              <div class="form-group">
                <%= f.text_area :content, class: "form-control", rows: 5 %>
              </div>
                <%= f.submit %>
            <% end %>
          <% else %>
            <%= link_to "Sign in to leave comments", new_user_session_path, class: "btn btn-default" %>
          <% end %>  
        </div>
      </div>
      
    </div>
  </div>
  

app/views/shared/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
      </button>
      <%= link_to "BACKSTARTER", root_path, class: "navbar-brand", :"data-no-turbolink" => true %>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <%= form_tag search_projects_path, method: :get, class:"navbar-form navbar-left", role: "search_project" do %>
          <div class="form-group">
            <%= text_field_tag :search_content, nil, placeholder: "Search for projects", class: "form-control search-bar" %> 
          </div>
          <%= button_tag(type: 'submit', class: "btn btn-default btn-search") do %>
            <span class="glyphicon glyphicon-search"></span> 
          <% end %>
        <% end %>
    
        <li><%= link_to "Categories", "/#categories" %></li>
        <% if user_signed_in? %>
          <% if current_user.admin %>
          <li><%= link_to "New project", new_project_path %></li>
          <% end %>
          <li><%= link_to "My Favorite", favorite_projects_path %></li>
          <li><%= link_to "Account", edit_user_registration_path %></li>
          <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
        <% end %>
        
      </ul>
    </div>
  </div>
</nav>